FROM benchflow/data-analyses-scheduler:dev

ENV PYSPARK_PYTHON python2.7
ENV PYTHONPATH /analysers/commons/
ENV ANALYSERS_PATH /analysers
	
COPY $TRAVIS_BUILD_DIR/analysers /analysers
COPY $TRAVIS_BUILD_DIR/test/python /test/pythonTests
COPY $TRAVIS_BUILD_DIR/test/spark /test/sparkTests
COPY $TRAVIS_BUILD_DIR/test/runTests.sh /test/
COPY $TRAVIS_BUILD_DIR/test/dependencies/pyspark-cassandra-assembly-0.3.5.jar /test/dependencies/
COPY $TRAVIS_BUILD_DIR/test/dependencies/log4j.properties $SPARK_HOME/conf/

RUN chmod +x /test/runTests.sh