analysers_settings: 
    - requirements: "faban"
      scripts: 
        - script_name: "faban"
          script_trial: "/analysers/trials/faban.py"
          script_experiment: "/analysers/experiments/faban.py"
    - requirements: "stats,properties"
      scripts: 
        - script_name: "ram"
          script_trial: "/analysers/trials/ram.py"
          script_experiment: "/analysers/experiments/ram.py"
        - script_name: "cpu"
          script_trial: "/analysers/trials/cpu.py"
          script_experiment: "/analysers/experiments/cpu.py"
        - script_name: "io"
          script_trial: "/analysers/trials/IO.py"
          script_experiment: "/analysers/experiments/IO.py"
    - requirements: "mysql"
      scripts: 
        - script_name: "execution_time"
          script_trial: "/analysers/trials/executionTime.py"
          script_experiment: "/analysers/experiments/executionTime.py"
        - script_name: "throughput"
          script_trial: "/analysers/trials/throughput.py"
          script_experiment: "/analysers/experiments/throughput.py"
        - script_name: "process_duration"
          script_trial: "/analysers/trials/processDuration.py"
          script_experiment: "/analysers/experiments/processDuration.py"
        - script_name: "number_of_process_instances"
          script_trial: "/analysers/trials/numberOfProcessInstances.py"
          script_experiment: "/analysers/experiments/numberOfProcessInstances.py"
        - script_name: "construct_duration"
          script_trial: "/analysers/trials/constructDuration.py"
          script_experiment: "/analysers/experiments/constructDuration.py"
        - script_name: "number_of_construct_instances"
          script_trial: "/analysers/trials/numberOfConstructInstances.py"
          script_experiment: "/analysers/experiments/numberOfConstructInstances.py"
        - script_name: "database_size"
          script_trial: "/analysers/trials/databaseSize.py"
          script_experiment: "/analysers/experiments/databaseSize.py"